In [1]:
import pandas as pd

df=pd.read_csv("/mnt/sde1/geth/nft_analyse_v1/data/sandwichBuy/csv/sandwich_withPrice.csv")    
    
addrSet=set()
for index in range(0,len(df),3):    
    fromAddress0=df.iloc[index]["from"]
    fromAddress1=df.iloc[index+2]["from"]
    addrSet.add(fromAddress0)
    addrSet.add(fromAddress1)
    
    # if df.iloc[index+1]["nftPrice"]==0:
    #     print(df.iloc[index+1])
    
print("total from: ",len(addrSet))
print("total attack: ",len(df)/3)

total from:  7
total attack:  41.0

In [3]:
df=pd.read_csv("/mnt/sde1/geth/nft_analyse_v1/data/sandwichBuy/csv/sandwich_withRevenue.csv")
print("total revenue: ",sum(df["revenue_dollar"]))
print("max revenue: ",max(df["revenue_dollar"]))
print("min revenue: ",min(df["revenue_dollar"]))

total revenue:  829474.8287913088
max revenue:  102958.52685722087
min revenue:  -26564.35151092387

In [5]:
df[df["revenue_dollar"]==max(df["revenue_dollar"])]

,blockNumber,timestamp,transactionHash,bidPrice,coinbase_transfer,nftPrice,ethPrice,revenue_eth,revenue_dollar
13,13816096,1639656258,0x1bc120a5f5dc268f305747b542c1b53ae896722239cc...,64.0,3.000000e+16,89.95,3972.841711,25.915587,102958.526857

In [6]:
df.sort_values("bidPrice")

,blockNumber,timestamp,transactionHash,bidPrice,coinbase_transfer,nftPrice,ethPrice,revenue_eth,revenue_dollar
2,13056183,1629382504,0xceef4add47560c1bc837b653eff788e991f5f4c11976...,0.01,2.650900e+19,49.0000,3175.947359,22.477049,71385.925145
30,14907558,1654410103,0xf33a83c746a103ed2c50b92715dbf2f8b096b01a6c6c...,0.10,4.442425e+19,63.4900,1809.011690,18.963347,34304.915600
29,14907555,1654410056,0xf5c453851ea46c40522186ebd692c4c167e4cb74287a...,0.10,4.455123e+19,59.9900,1809.011690,15.335815,27742.668118
1,13012948,1628805719,0x0ee2b4d6f1a53082e1c38cab2584a13e8f1ffba5f3c4...,41.00,1.000000e+17,43.0000,3040.910452,1.869530,5685.074683
0,13000672,1628641450,0x4479d31a5b17ef3b36ef17968e8f1dff6c8afd5b10be...,42.50,1.082609e+17,48.0000,3173.150316,5.387109,17094.105593
15,14003541,1642162116,0xe2f61174a46d9a9b62bd6585863eb3c4d796c2fdc67e...,50.00,2.526591e+18,61.9500,3307.870930,9.410162,31127.602523
28,14756952,1652300429,0x9d7b0c9b53a4095acfb71d13c846f87c57e23c831257...,50.00,2.845939e+17,55.9500,2080.302186,5.646453,11746.329254
24,14632541,1650601725,0xd019d779af165b7b731da9acbfc86b0c007f70424f5a...,54.00,2.460000e+16,59.9500,2961.390942,5.921361,17535.463913
14,13916211,1640995681,0xa1bf2e010cb28626c834033529713487d57b1e2897c6...,55.00,1.240155e+18,69.9900,3755.769796,13.741470,51609.798171
17,14025107,1642449950,0xb059dc9b6e2b502ddbed84ab6b9243f45310e2f97ad7...,57.00,1.878290e+17,60.4900,3210.454288,3.277138,10521.101339
25,14636977,1650661674,0x67ee0be1041b5c595b28e5d4c80fe1dfdac3bba5d274...,57.00,4.740000e+16,67.1621,2961.390942,10.106665,29929.787096
27,14664342,1651033354,0x235fd39ffda6045b789bb1ce5f7664ea768b562181db...,57.50,2.160000e+16,57.5000,2887.388697,-0.025228,-72.843029
16,14024059,1642436491,0x08fec5bea7bcb83fa3a246f2c178efb29e5c60a974da...,58.12,4.236599e+16,66.4900,3210.454288,8.311838,26684.776299
32,15246975,1659226674,0xe24c7bface77093003c2d16bbc477779865916d2e29f...,60.00,2.769685e+18,63.0000,1684.082034,0.229416,386.356008
12,13811409,1639593554,0xaab3a135939a23e78900b517d4c8a6083e25a8cc664d...,60.00,4.486674e+17,64.9900,4018.645138,4.526995,18192.386382
26,14649260,1650828019,0x21c3f8de7ed8fa3143625fb205b8b0e10981066cebfe...,61.00,3.900000e+16,62.9500,2914.956803,1.904530,5551.621987
33,15372301,1660925704,0xa4dacc9c6726103ed6701a3c5f0b1305cb7f8a2287b7...,62.00,5.201962e+17,65.9900,1609.162994,3.467722,5580.130187
36,15390973,1661181126,0x1b65ada0693484c5745b3466f64d8af5be24a8b3678e...,62.00,7.898946e+17,67.9900,1622.667807,5.198101,8434.790655
34,15382169,1661060497,0xbe6e1593ea6f9d141eb2d6666c3b223c4228d182eb68...,63.00,7.633871e+17,66.9900,1620.986945,3.226191,5229.613887
13,13816096,1639656258,0x1bc120a5f5dc268f305747b542c1b53ae896722239cc...,64.00,3.000000e+16,89.9500,3972.841711,25.915587,102958.526857
31,15217979,1658836955,0x4602e13c91425f7d704eac8175366c7216e7b804924c...,67.50,3.867343e+17,74.4900,1449.367208,6.601211,9567.578456
21,14302351,1646153904,0x7c7986a5ddd242c0df0a9f16bcaacda9cac815fa297a...,70.00,1.811514e+17,81.9500,2969.227463,11.762964,34926.915157
22,14450780,1648148997,0x3afd6059d65c3925063bd7fc80f260022c9fed04800b...,70.00,5.100000e+16,70.9500,3110.430960,0.890496,2769.826488
35,15390487,1661174869,0xa0fad78835840fbc6ebcb1b71ab3a39bcc0e5af5c343...,71.00,1.793025e+16,75.0000,1622.667807,3.980635,6459.247640
23,14521046,1649095590,0x748332a389b6fef22cb5a6a1deffcffea91305871ffa...,73.00,3.960000e+16,75.0000,3528.793919,1.954175,6895.879578
10,13752803,1638800592,0x5d4bac834b05f5af92042e42f0731710e6cb48663f5b...,73.00,3.553581e+16,84.9900,4345.504874,11.943652,51901.199528
37,15493236,1662594506,0xe123d3d8d42b235d4c5e4c8eace22424ccb9952c6480...,79.00,1.170000e+16,89.9500,1626.462558,10.937142,17788.852255
18,14093579,1643364993,0x85abee9f3b65065490b7433782ab79afc341b693b613...,81.50,0.000000e+00,84.9400,2540.247077,3.407022,8654.678875
11,13752957,1638802810,0x63f964f41da3d64a4b463a411cf3ae22ae0d8204ce24...,85.00,5.372850e+16,98.9900,4345.504874,13.923312,60503.820507
8,13550671,1636035002,0xe796ad986a850efa8e81d41a8821a1b1cd662b87ac19...,86.00,4.320000e+16,89.0000,4522.064376,2.942458,13305.985666
5,13488041,1635184215,0x836d2ae87555dec2be129735e240fb96c6b6e69cefa3...,90.00,8.475000e+16,95.9500,4204.490524,5.853687,24611.769599
6,13507748,1635451295,0x0d1b11ff829842806732ab970602b13185b301ba9744...,99.00,1.417500e+17,92.9500,4275.237414,-6.213538,-26564.351511
3,13428480,1634380025,0xed61e6c652e54e6132661b79badece767270eff13740...,101.00,4.875000e+16,103.9500,3833.837841,2.894983,11098.895746
19,14116306,1643667310,0xad096bcae135baa14911930fabb50a1bb0b4fda21959...,103.00,8.100000e+16,94.9500,2687.235361,-8.144512,-21886.220096
9,13723379,1638393392,0x3b327762e3214a7cae8959c9221067b5120206779aa4...,105.00,4.200000e+16,109.9500,4576.921609,4.890992,22385.685086
4,13456578,1634759755,0x7bf128dba6d84bbb649c84f4f9df159177cadce0429b...,108.88,7.500000e+16,123.0000,4150.176648,14.036266,58252.985066
7,13512971,1635523009,0x553962f1774a7a6f85f7819efd0a471de169d943e0b6...,110.00,9.540000e+16,121.9500,4432.431549,11.834554,52455.850694
20,14166979,1644344189,0xd798b61ef705278e890ec096e4dc74dbcf16ee2df013...,115.00,2.593214e+17,119.9900,3115.882185,4.723574,14718.099388

In [4]:
df[df["revenue_dollar"]<0]

NameError: name 'df' is not defined

In [12]:
df=pd.read_csv("/mnt/sde1/geth/nft_analyse_v1/data/sandwichBuy/csv/punkBidEntered.csv")
df[df["punkIndex"]==2837]

,blockNumber,transactionHash,transactionIndex,punkIndex,fromAddress,price
759,14781395,0x1aad3093b4f22c5311c2856a1a62f22572b52e5d25b8...,39,2837,0x1919db36ca2fa2e15f9000fd9cdc2edcf863e685,47500000000000000000
760,14781609,0x31380e1edef4e16dfb4eef92ad2aa1b02d649c56543b...,25,2837,0xee698b39655285d4009a2958d62bb06bc040ef0c,10000000000000000
2987,14743812,0x605dced3f7e3e96b85af14387a5bd540ebddbfded8c1...,3,2837,0x9e4dec4a9941ca7713b48c17f85f27df9a60db48,67162100000000000000
5127,14636650,0xe3669dcfd1a6c4091c117cc582a617f81f325ca9fe02...,181,2837,0xaea8e3bd369217cc6e3e6abddf0da318fba8e59b,57000000000000000000
5129,14636977,0xec3ac5f34aed1f082f481aeda553bf41d3cd69b10d29...,0,2837,0x1919db36ca2fa2e15f9000fd9cdc2edcf863e685,57000000000000000020

In [13]:
df=pd.read_csv("/mnt/sde1/geth/nft_analyse_v1/data/sandwichBuy/csv/punkBought.csv")
df[df["punkIndex"]==2837]

,blockNumber,transactionHash,transactionIndex,punkIndex,fromAddress,toAddress,price
488,14781630,0xfdb91eb3a2442f7f7a5798a9b33cc816f2aed7965375...,67,2837,0x44a088f8567505894b50bfe626c4bc7ad6850664,0x0fc584529a2aefa997697fafacba5831fac0c22d,0
489,14781630,0xfdb91eb3a2442f7f7a5798a9b33cc816f2aed7965375...,67,2837,0x0fc584529a2aefa997697fafacba5831fac0c22d,0x269616d549d7e8eaa82dfb17028d0b212d11232a,0
2244,14743812,0x0bb96691b5b788f8164407a0fb4b3bb579d0d635b176...,4,2837,0x1919db36ca2fa2e15f9000fd9cdc2edcf863e685,0x0000000000000000000000000000000000000000,0
3732,14636977,0x3326584109daa78a76d43e99f8157ee1b91a0152ec79...,1,2837,0x0d5c661b7bc1628e6da0cabf5ba0dd7ceb1a73d6,0x0000000000000000000000000000000000000000,0

In [ ]:
14743812